version: "3"

services:
  valheim:
    build:
      context: ./
      dockerfile: Dockerfile
    image: valheim:latest
    container_name: valheim
    environment:
      - SERVER_NAME=MyAwesomeServer # Change this to your server name
      - WORLD_NAME=MyAwesomeWorld # Change this to your world name
      - SERVER_PASS=MySuperSecretPassword # Change this to your server password
      - PUBLIC=0  # Change this to 1 if you want your server to be public
      - UPDATE=true 
      - PORT=2456
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
      - "27015:27015/tcp"
    volumes:  # Change these paths to match the locations in the pre-setup.sh script
      - "/home/ubuntu/docker/containers/valheim/data:/data:rw"
      - "/home/ubuntu/docker/containers/valheim/server:/valheim:rw"
      - "/home/ubuntu/docker/containers/valheim/logs:/home/steam/logs:rw"
    restart: unless-stopped
