version: "3"

services:
  valheim:
    build:
      context: /home/ubuntu/docker/containers/valheim/files
      dockerfile: Dockerfile
    container_name: valheim
    environment:
      - SERVER_NAME=MyServer
      - WORLD_NAME=Server
      - SERVER_PASS=password
      - PUBLIC=0
      - UPDATE=true
      - PORT=2456
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
      - "27015:27015/tcp"
    volumes:
      - "/home/ubuntu/docker/storage/valheim/data:/data:rw"
      - "/home/ubuntu/docker/containers/valheim/server:/valheim:rw"
      - "/home/ubuntu/docker/logs/valheim.log:/home/ubuntu/docker/logs/valheim.log"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/bash", "/home/steam/healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
