version: "3"

services:
  valheim2:
    build:
      context: ./valheim-arm64
      dockerfile: Dockerfile
    container_name: valheim2
    environment:
      - SERVER_NAME=TheDistrict2
      - WORLD_NAME=District2
      - SERVER_PASS=password
      - PUBLIC=0
      - UPDATE=true
      - PORT=2456
      - INSTANCEID=2
    networks:
      - valheim2_net
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
      - "27015:27015/tcp"
    volumes:
      - "./valheim2/data:/data:rw"
      - "./valheim2/server:/valheim:rw"
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 5m
      timeout: 30s
      retries: 1
      start_period: 15m

networks:
  valheim2_net:
    name: valheim2_net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: 10.0.0.58