version: "3"

services:
  valheim1:
    build:
      context: ./valheim-arm64
      dockerfile: Dockerfile
    container_name: valheim1
    environment:
      - SERVER_NAME=TheDistrict
      - WORLD_NAME=District
      - SERVER_PASS=password
      - PUBLIC=0
      - UPDATE=true
      - PORT=2456
      - INSTANCEID=1
    networks:
      - valheim1_net
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
      - "27015:27015/tcp"
    volumes:
      - "./valheim1/data:/data:rw"
      - "./valheim1/server:/valheim:rw"
    restart: unless-stopped
    init: true
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 5m
      timeout: 30s
      retries: 1
      start_period: 15m

networks:
  valheim1_net:
    name: valheim1_net
    driver: bridge
    driver_opts:
      parent: enp1s0
      com.docker.network.bridge.host_binding_ipv4: 10.0.0.67
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      config:
      - subnet: 172.21.25.0/24
        gateway: 172.21.25.1