#!/bin/bash
set -eo pipefail

# Delete all old files online
dbxcli ls /Valheim-Worlds -l | awk 'NR>1 {print $NF}' | xargs -I '{}' sh -c 'dbxcli rm -f {}'

# Upload all valheim files
find /home/ubuntu/valheim1/data/worlds_local/ -type f ! -name "*backup*" ! -name "*.old" ! -name "*.new" | xargs -I '{}' sh -c 'dbxcli put {} /Valheim-Worlds/$(basename {})'
find /home/ubuntu/valheim2/data/worlds_local/ -type f ! -name "*backup*" ! -name "*.old" ! -name "*.new" | xargs -I '{}' sh -c 'dbxcli put {} /Valheim-Worlds/$(basename {})'
 
